homepage: "https://msgpack.org/"
language: python
primary_contact: "songofacandy@gmail.com"
main_repo: "https://github.com/msgpack/msgpack-python.git"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
